package com.example.ypackfood.enumClasses

enum class ErrorEnum(val title: String) {
    AUTHENTICATION_REQUIRED("AUTHENTICATION_REQUIRED"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    TOKEN_EXPIRED_OR_INVALID("TOKEN_EXPIRED_OR_INVALID"),
    USER_IS_BANNED("USER_IS_BANNED"),
    DELETED_DISH_IN_ORDER("DELETED_DISH_IN_ORDER"),
    INCORRECT_DATA_FOR_DISH("INCORRECT_DATA_FOR_DISH"),
    INCORRECT_DATA_FOR_ADDON("INCORRECT_DATA_FOR_ADDON"),
    INVALID_TOTAL_PRICE("INVALID_TOTAL_PRICE"),
    USER_ALREADY_EXIST("USER_ALREADY_EXIST"),
    INCORRECT_PHONE_NUMBER_OR_PASSWORD("INCORRECT_PHONE_NUMBER_OR_PASSWORD"),
    ADDRESS_REQUIRED("ADDRESS_REQUIRED"),
    ENTITY_ALREADY_EXISTS("ENTITY_ALREADY_EXISTS"),
    OUT_OF_BOUNDS("OUT_OF_BOUNDS"),
    MUST_NOT_BE_EMPTY("MUST_NOT_BE_EMPTY"),
    INVALID_EMAIL("INVALID_EMAIL"),
    UNDEFINED("UNDEFINED"),
    ALLOWED_NUMBER_OF_LOGIN_ATTEMPTS_EXCEEDED("ALLOWED_NUMBER_OF_LOGIN_ATTEMPTS_EXCEEDED")
}